package(default_visibility = ["//visibility:public"])

java_library(
    name = "java",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party:guava",
        "//third_party:junit4",
    ],
)
