package(default_visibility = ["//visibility:public"])

java_library(
    name = "java",
    srcs = ["JavaCycle.java"],
    deps = [
        # "//mixed-lib/src/main/scala/com/example/cyclic:scala",
    ],
)
