java_test(
    name = "test",
    srcs = glob(["*.scala"]),
    size = "small",
    deps = [
        "//mixed-lib/src/main/java/com/example:java",
        "//mixed-lib/src/main/scala/com/example:scala",
        "//third_party:junit4",
    ],
)
